import assert from "node:assert/strict";
import test from "node:test";
import type { AIProvider } from "./aiProvider.js";
import { generateWithFallback } from "./generateWithFallback.js";
import { prisma } from "../db/prisma.js";
import { buildTraceContext, createAIUsageTrace } from "../services/aiUsageTraceService.js";
import { LOCAL_SANDBOX_MODEL, LOCAL_SANDBOX_PROVIDER_ID, LOCAL_SANDBOX_PROVIDER_NAME } from "../services/aiProviderRegistry.js";

async function createTestTrace(label: string) {
  const trace = await createAIUsageTrace({
    triggerType: "SYSTEM_PROCESS",
    triggerLabel: label,
    sourceType: "MANUAL_TEST",
    sourceId: label,
    operation: "generate_with_fallback_test",
    purpose: "Generate with fallback test",
    attributionStatus: "PARTIAL"
  });
  return buildTraceContext({
    traceId: trace.traceId,
    triggerType: "SYSTEM_PROCESS",
    sourceType: "MANUAL_TEST",
    sourceId: label,
    operation: "generate_with_fallback_test",
    purpose: "Generate with fallback test",
    attributionStatus: "PARTIAL"
  });
}

test("failed AI provider falls back to local sandbox baseline without throwing", async () => {
  const failingProvider: AIProvider = {
    name: "openai",
    model: "failing-model",
    async generateAgentResponse() {
      throw new Error("simulated provider failure");
    }
  };

  const traceContext = await createTestTrace(`fallback-sandbox-${Date.now()}`);
  const result = await generateWithFallback(failingProvider, {
    command: "Build the throne room processing flow",
    mode: "BUILD",
    agentName: "Seraphine",
    agentRole: "Royal Architect",
    agentSkills: ["architecture"],
    systemPrompt: "You are the Royal Architect.",
    responseStyle: "structured"
  }, traceContext);

  assert.equal(result.providerName, LOCAL_SANDBOX_PROVIDER_NAME);
  assert.equal(result.providerId, LOCAL_SANDBOX_PROVIDER_ID);
  assert.equal(result.modelUsed, LOCAL_SANDBOX_MODEL);
  assert.match(result.response, /Royal Architect/);
  assert.match(result.fallbackNotice ?? "", /simulated provider failure/);
  assert.match(result.fallbackNotice ?? "", /Final answer generated by Local Sandbox Baseline \/ local-sandbox-baseline/);
  assert.ok(result.usage.totalTokens > 0);

  const step = await prisma.aIUsageTraceStep.findFirst({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_FALLBACK" }
  });
  assert.ok(step);
  assert.equal(step.providerName, LOCAL_SANDBOX_PROVIDER_NAME);
  assert.equal(step.providerType, "sandbox");
  assert.equal(step.model, LOCAL_SANDBOX_MODEL);
  assert.match(JSON.stringify(step.metadata), /fallbackReason/);
});

test("fallback chain tries the next configured provider before local sandbox baseline", async () => {
  const failingProvider: AIProvider = {
    name: "deepseek",
    model: "deepseek-chat",
    async generateAgentResponse() {
      throw new Error("timeout");
    }
  };
  const succeedingProvider: AIProvider = {
    name: "openrouter",
    model: "openai/gpt-4o-mini",
    async generateAgentResponse() {
      return {
        response: "OpenRouter counsel",
        usage: { promptTokens: 10, completionTokens: 5, totalTokens: 15 }
      };
    }
  };

  const traceContext = await createTestTrace(`fallback-chain-${Date.now()}`);
  const result = await generateWithFallback([failingProvider, succeedingProvider], {
    command: "Build a fallback chain",
    mode: "BUILD",
    agentName: "Seraphine",
    agentRole: "Royal Architect",
    agentSkills: ["architecture"],
    systemPrompt: "You are the Royal Architect.",
    responseStyle: "structured"
  }, traceContext);

  assert.equal(result.providerName, "OpenRouter");
  assert.deepEqual(result.attemptedProviders, ["deepseek", "openrouter"]);
  assert.match(result.fallbackNotice ?? "", /returned timeout/);
  assert.match(result.fallbackNotice ?? "", /Final answer generated by OpenRouter \/ openai\/gpt-4o-mini/);
});

test("generateWithFallback rejects missing trace context", async () => {
  const provider: AIProvider = {
    name: "mock",
    model: "deterministic-mock-v1",
    async generateAgentResponse() {
      return {
        response: "ok",
        usage: { promptTokens: 1, completionTokens: 1, totalTokens: 2 }
      };
    }
  };

  await assert.rejects(
    () => generateWithFallback(provider, {
      command: "No trace",
      mode: "ASK",
      agentName: "Aurelian",
      agentRole: "Grand Vizier",
      agentSkills: [],
      systemPrompt: "test",
      responseStyle: "brief"
    }, undefined as never),
    /requires trace context/
  );
});

test("primary provider succeeds without triggering fallback", async () => {
  const successProvider: AIProvider = {
    name: "openrouter-free",
    model: "nvidia/nemotron-3-super-120b-a12b:free",
    async generateAgentResponse() {
      return {
        response: "Primary counsel response",
        usage: { promptTokens: 10, completionTokens: 5, totalTokens: 15 }
      };
    }
  };

  const traceContext = await createTestTrace(`primary-success-${Date.now()}`);
  const result = await generateWithFallback(successProvider, {
    command: "Advise on kingdom growth",
    mode: "ASK",
    agentName: "Aurelian",
    agentRole: "Grand Vizier",
    agentSkills: ["counsel"],
    systemPrompt: "You are the Grand Vizier.",
    responseStyle: "concise"
  }, traceContext);

  assert.equal(result.fallbackUsed, false);
  assert.equal(result.fallbackNotice, undefined);
  assert.equal(result.response, "Primary counsel response");
  assert.equal(result.providerId, "openrouter-free");

  const fallbackStep = await prisma.aIUsageTraceStep.findFirst({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_FALLBACK" }
  });
  assert.equal(fallbackStep, null);
});

test("primary timeout triggers fallback to configured model before local sandbox", async () => {
  const timeoutProvider: AIProvider = {
    name: "openrouter-free",
    model: "nvidia/nemotron-3-super-120b-a12b:free",
    async generateAgentResponse() {
      const err = new Error("PROVIDER_TIMEOUT: openrouter-free timed out after 20000ms");
      (err as any).errorCode = "PROVIDER_TIMEOUT";
      throw err;
    }
  };
  const fallbackModelProvider: AIProvider = {
    name: "openrouter-free",
    model: "openai/gpt-oss-120b:free",
    async generateAgentResponse() {
      return {
        response: "Fallback model counsel",
        usage: { promptTokens: 8, completionTokens: 4, totalTokens: 12 }
      };
    }
  };

  const traceContext = await createTestTrace(`timeout-model-fallback-${Date.now()}`);
  const result = await generateWithFallback([timeoutProvider, fallbackModelProvider], {
    command: "Advise on kingdom growth",
    mode: "ASK",
    agentName: "Aurelian",
    agentRole: "Grand Vizier",
    agentSkills: ["counsel"],
    systemPrompt: "You are the Grand Vizier.",
    responseStyle: "concise"
  }, traceContext);

  assert.equal(result.fallbackUsed, true);
  assert.equal(result.response, "Fallback model counsel");
  assert.match(result.fallbackNotice ?? "", /PROVIDER_TIMEOUT/);

  const failedStep = await prisma.aIUsageTraceStep.findFirst({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_CALL_FAILED" }
  });
  assert.ok(failedStep, "trace must record failed primary attempt");
  assert.match(failedStep.errorMessage ?? "", /PROVIDER_TIMEOUT/);

  const fallbackStep = await prisma.aIUsageTraceStep.findFirst({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_FALLBACK" }
  });
  assert.ok(fallbackStep, "trace must record fallback transition");
});

test("multiple fallback model failures before reaching local sandbox", async () => {
  function failingProvider(name: string, model: string): AIProvider {
    return {
      name,
      model,
      async generateAgentResponse() {
        throw new Error(`${name}/${model} failed`);
      }
    };
  }

  const traceContext = await createTestTrace(`multi-fallback-${Date.now()}`);
  const result = await generateWithFallback(
    [
      failingProvider("openrouter-free", "nvidia/nemotron-3-super-120b-a12b:free"),
      failingProvider("openrouter-free", "openai/gpt-oss-120b:free"),
      failingProvider("openrouter-free", "deepseek/deepseek-v4-flash")
    ],
    {
      command: "Advise on kingdom stability",
      mode: "ASK",
      agentName: "Aurelian",
      agentRole: "Grand Vizier",
      agentSkills: ["counsel"],
      systemPrompt: "You are the Grand Vizier.",
      responseStyle: "concise"
    },
    traceContext
  );

  assert.equal(result.providerName, LOCAL_SANDBOX_PROVIDER_NAME);
  assert.equal(result.finalModel, LOCAL_SANDBOX_MODEL);
  assert.equal(result.fallbackUsed, true);

  const failedSteps = await prisma.aIUsageTraceStep.findMany({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_CALL_FAILED" }
  });
  assert.equal(failedSteps.length, 3, "trace must record all three provider failures");
});

test("provider fallback activates after model fallbacks exhausted", async () => {
  const primaryProvider: AIProvider = {
    name: "openrouter-free",
    model: "nvidia/nemotron-3-super-120b-a12b:free",
    async generateAgentResponse() {
      throw new Error("primary model timeout");
    }
  };
  const providerFallback: AIProvider = {
    name: "deepseek",
    model: "deepseek-chat",
    async generateAgentResponse() {
      return {
        response: "DeepSeek provider fallback counsel",
        usage: { promptTokens: 12, completionTokens: 6, totalTokens: 18 }
      };
    }
  };

  const traceContext = await createTestTrace(`provider-fallback-${Date.now()}`);
  const result = await generateWithFallback([primaryProvider, providerFallback], {
    command: "Advise on strategic priorities",
    mode: "PLAN",
    agentName: "Seraphine",
    agentRole: "Royal Architect",
    agentSkills: ["planning"],
    systemPrompt: "You are the Royal Architect.",
    responseStyle: "structured"
  }, traceContext);

  assert.equal(result.providerName, "DeepSeek");
  assert.equal(result.fallbackUsed, true);
  assert.match(result.fallbackNotice ?? "", /primary model timeout/);
  assert.deepEqual(result.attemptedProviders, ["openrouter-free", "deepseek"]);
});

test("local sandbox is final fallback when all providers fail", async () => {
  const traceContext = await createTestTrace(`sandbox-final-${Date.now()}`);
  const result = await generateWithFallback(
    [
      {
        name: "openrouter-free",
        model: "bad-model-1",
        async generateAgentResponse() { throw new Error("model 1 failed"); }
      },
      {
        name: "deepseek",
        model: "deepseek-chat",
        async generateAgentResponse() { throw new Error("provider failed"); }
      }
    ],
    {
      command: "Final fallback test",
      mode: "ASK",
      agentName: "Aurelian",
      agentRole: "Grand Vizier",
      agentSkills: [],
      systemPrompt: "You are the Grand Vizier.",
      responseStyle: "concise"
    },
    traceContext
  );

  assert.equal(result.providerName, LOCAL_SANDBOX_PROVIDER_NAME);
  assert.equal(result.providerId, LOCAL_SANDBOX_PROVIDER_ID);
  assert.equal(result.modelUsed, LOCAL_SANDBOX_MODEL);
  assert.equal(result.fallbackUsed, true);
  assert.ok(result.response.length > 0);

  const steps = await prisma.aIUsageTraceStep.findMany({
    where: { traceId: traceContext.traceId }
  });
  const stepTypes = steps.map((s) => s.stepType);
  assert.ok(stepTypes.includes("PROVIDER_CALL_FAILED"), "trace must show failures");
  assert.ok(stepTypes.includes("PROVIDER_FALLBACK"), "trace must show fallback transition");
  assert.ok(stepTypes.includes("PROVIDER_CALL_SUCCESS"), "trace must show final success");
});

test("Grand Vizier synthesis: primary fails, first fallback fails, second fallback succeeds, sandbox not called", async () => {
  const called: string[] = [];

  function trackingProvider(name: string, model: string, fail: boolean): AIProvider {
    return {
      name,
      model,
      async generateAgentResponse(input) {
        called.push(`${name}/${model}`);
        if (fail) throw new Error(`${name}/${model} unavailable`);
        return {
          response: `Response from ${model}`,
          usage: { promptTokens: 8, completionTokens: 4, totalTokens: 12 }
        };
      }
    };
  }

  const traceContext = await createTestTrace(`synthesis-second-fallback-${Date.now()}`);
  const result = await generateWithFallback(
    [
      trackingProvider("test-fallback-provider", "nvidia/nemotron-3-super-120b-a12b:free", true),
      trackingProvider("test-fallback-provider", "openai/gpt-oss-120b:free", true),
      trackingProvider("test-fallback-provider", "openrouter/owl-alpha", false)
    ],
    {
      command: "Synthesize council output",
      mode: "ASK",
      agentName: "Aurelian",
      agentRole: "Grand Vizier",
      agentSkills: ["synthesis"],
      systemPrompt: "You are the Grand Vizier.",
      responseStyle: "concise"
    },
    traceContext
  );

  assert.equal(result.finalModel, "openrouter/owl-alpha", "Second fallback model must be used");
  assert.equal(result.fallbackUsed, true);
  assert.ok(!called.includes(`${LOCAL_SANDBOX_PROVIDER_ID}/${LOCAL_SANDBOX_MODEL}`), "Local sandbox must not be called when an API model succeeds");
  assert.ok(result.finalProviderId !== LOCAL_SANDBOX_PROVIDER_ID, "Result must not come from sandbox");

  const successStep = await prisma.aIUsageTraceStep.findFirst({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_CALL_SUCCESS" }
  });
  assert.ok(successStep, "Trace must record a successful provider call");
  assert.equal(successStep.model, "openrouter/owl-alpha", "Success step must record the correct fallback model");

  const failedSteps = await prisma.aIUsageTraceStep.findMany({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_CALL_FAILED" }
  });
  assert.equal(failedSteps.length, 2, "Trace must record exactly two failures (primary and first fallback)");
});

test("all OpenRouter fallbackModels fail: local sandbox called exactly once as final fallback", async () => {
  const traceContext = await createTestTrace(`all-models-fail-${Date.now()}`);
  const result = await generateWithFallback(
    [
      {
        name: "openrouter-free",
        model: "nvidia/nemotron-3-super-120b-a12b:free",
        async generateAgentResponse() { throw new Error("model 1 unavailable"); }
      },
      {
        name: "openrouter-free",
        model: "openai/gpt-oss-120b:free",
        async generateAgentResponse() { throw new Error("model 2 unavailable"); }
      },
      {
        name: "openrouter-free",
        model: "openrouter/owl-alpha",
        async generateAgentResponse() { throw new Error("model 3 unavailable"); }
      },
      {
        name: "openrouter-free",
        model: "deepseek/deepseek-v4-flash",
        async generateAgentResponse() { throw new Error("model 4 unavailable"); }
      }
    ],
    {
      command: "Advise on kingdom growth",
      mode: "ASK",
      agentName: "Aurelian",
      agentRole: "Grand Vizier",
      agentSkills: ["counsel"],
      systemPrompt: "You are the Grand Vizier.",
      responseStyle: "concise"
    },
    traceContext
  );

  assert.equal(result.providerName, LOCAL_SANDBOX_PROVIDER_NAME, "Sandbox must be the final result provider");
  assert.equal(result.providerId, LOCAL_SANDBOX_PROVIDER_ID);
  assert.equal(result.modelUsed, LOCAL_SANDBOX_MODEL);
  assert.equal(result.fallbackUsed, true);

  const successSteps = await prisma.aIUsageTraceStep.findMany({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_CALL_SUCCESS" }
  });
  assert.equal(successSteps.length, 1, "Sandbox must be called exactly once as final fallback");
  assert.equal(successSteps[0]!.providerType, "sandbox", "The single successful call must be the sandbox");

  const failedSteps = await prisma.aIUsageTraceStep.findMany({
    where: { traceId: traceContext.traceId, stepType: "PROVIDER_CALL_FAILED" }
  });
  assert.equal(failedSteps.length, 4, "All 4 configured API models must be recorded as failures before sandbox");
});

test.after(async () => {
  await prisma.aIUsageTrace.deleteMany({ where: { operation: "generate_with_fallback_test" } });
});
