import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { cn, timeAgo } from "@/lib/utils";
import type { KingdomActivityItemDto, NextActionItem } from "@/types/api";

export type ProvenanceLink = { label: string; to?: string };

export type ProvenanceLinksProps = {
  /** Where this item came from, e.g. "Council Session #55". Links to `source.to` when present. */
  source?: ProvenanceLink;
  /** Who produced it, e.g. "Royal Planner". */
  generatedBy?: string | null;
  /** Optional related entities/initiatives. */
  related?: ProvenanceLink[];
  /** ISO timestamp / Date the item was last updated. */
  updatedAt?: string | Date | null;
  className?: string;
};

function shortId(id: string) {
  return id.length > 10 ? `${id.slice(0, 8)}…` : id;
}

function ProvenanceRow({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex items-baseline gap-2">
      <span className="w-24 shrink-0 text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70">{label}</span>
      <span className="min-w-0 flex-1 truncate text-xs text-foreground/85">{children}</span>
    </div>
  );
}

function LinkOrText({ link }: { link: ProvenanceLink }) {
  if (link.to) {
    return (
      <Link to={link.to} className="text-primary underline-offset-2 hover:underline">
        {link.label}
      </Link>
    );
  }
  return <span>{link.label}</span>;
}

/**
 * "Where did this come from?" — a compact, reusable provenance block.
 * Renders Source / Generated By / Related / Updated rows, omitting any that are empty.
 * Every important card should answer this so the King is never shown an isolated record.
 */
export function ProvenanceLinks({ source, generatedBy, related, updatedAt, className }: ProvenanceLinksProps) {
  const hasRelated = related && related.length > 0;
  if (!source && !generatedBy && !hasRelated && !updatedAt) return null;

  return (
    <div className={cn("space-y-1 border-t border-border/40 pt-2", className)}>
      {source && (
        <ProvenanceRow label="Source">
          <LinkOrText link={source} />
        </ProvenanceRow>
      )}
      {generatedBy && <ProvenanceRow label="Generated By">{generatedBy}</ProvenanceRow>}
      {hasRelated && (
        <ProvenanceRow label="Related">
          <span className="inline-flex flex-wrap gap-x-2">
            {related!.map((link, i) => (
              <LinkOrText key={`${link.label}-${i}`} link={link} />
            ))}
          </span>
        </ProvenanceRow>
      )}
      {updatedAt && <ProvenanceRow label="Updated">{timeAgo(updatedAt)}</ProvenanceRow>}
    </div>
  );
}

// ── Adapters from existing DTOs ───────────────────────────────────────────────

const ENTITY_ROUTES: Record<string, string> = {
  WorkOrder: "/work-orders",
  CouncilSession: "/council",
  AutomationJob: "/automation-jobs",
  AutomationCandidate: "/living-loop",
  Project: "/projects",
  ProjectInboxItem: "/project-inbox",
  Notice: "/notices",
  Matter: "/matters",
  RoyalReport: "/reports",
  Memory: "/memory",
  HandoffBrief: "/work-orders",
  AgentKnowledgeCandidate: "/knowledge-lab"
};

/** Build provenance props from a NextActionItem's `provenance` + `routeTo`. */
export function provenanceFromNextAction(item: NextActionItem): ProvenanceLinksProps {
  const p = item.provenance;
  return {
    source: { label: `${p.source} #${shortId(p.id)}`, to: item.routeTo ?? ENTITY_ROUTES[p.source] },
    updatedAt: p.observedAt
  };
}

/** Build provenance props from a KingdomActivityItem's `sourceReference`. */
export function provenanceFromActivity(item: KingdomActivityItemDto): ProvenanceLinksProps {
  const ref = item.sourceReference;
  return {
    source: { label: `${ref.entityType} #${shortId(ref.entityId)}`, to: ref.routeTo },
    generatedBy: item.actor,
    updatedAt: item.timestamp
  };
}
