import { render, screen } from "@testing-library/react";
import type { ReactNode } from "react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it } from "vitest";
import type { KingdomActivityItemDto, NextActionItem } from "@/types/api";
import { ProvenanceLinks, provenanceFromActivity, provenanceFromNextAction } from "./ProvenanceLinks";

function renderWithRouter(ui: ReactNode) {
  return render(<MemoryRouter>{ui}</MemoryRouter>);
}

describe("ProvenanceLinks", () => {
  it("renders source / generated by / related / updated rows", () => {
    renderWithRouter(
      <ProvenanceLinks
        source={{ label: "Council Session #55", to: "/council" }}
        generatedBy="Royal Planner"
        related={[{ label: "Provider Routing Initiative", to: "/projects/p1" }]}
        updatedAt={new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()}
      />
    );

    expect(screen.getByText("Source")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Council Session #55" })).toHaveAttribute("href", "/council");
    expect(screen.getByText("Royal Planner")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Provider Routing Initiative" })).toHaveAttribute("href", "/projects/p1");
    expect(screen.getByText("2h ago")).toBeInTheDocument();
  });

  it("renders nothing when no provenance is supplied", () => {
    const { container } = renderWithRouter(<ProvenanceLinks />);
    expect(container).toBeEmptyDOMElement();
  });

  it("renders source as plain text when no link is provided", () => {
    renderWithRouter(<ProvenanceLinks source={{ label: "System" }} />);
    expect(screen.getByText("System")).toBeInTheDocument();
    expect(screen.queryByRole("link")).toBeNull();
  });

  it("builds props from a NextActionItem (source label + routeTo)", () => {
    const item: NextActionItem = {
      id: "WorkOrder:wo-1",
      entityType: "WorkOrder",
      entityId: "wo-1",
      title: "t",
      actionLabel: "Review",
      why: "w",
      priority: 1,
      riskLevel: "HIGH",
      abstractState: "AWAITING_DECISION",
      isEscalated: false,
      isBlocking: 0,
      routeTo: "/work-orders",
      ageHours: 1,
      provenance: { source: "WorkOrder", id: "wo-1", observedAt: new Date().toISOString() }
    };
    renderWithRouter(<ProvenanceLinks {...provenanceFromNextAction(item)} />);
    expect(screen.getByRole("link", { name: /WorkOrder #wo-1/i })).toHaveAttribute("href", "/work-orders");
  });

  it("builds props from a KingdomActivityItem (source + actor)", () => {
    const item: KingdomActivityItemDto = {
      id: "act-1",
      timestamp: new Date().toISOString(),
      actor: "Local Runner",
      type: "AUTOMATION_JOB",
      summary: "Validation job completed",
      sourceReference: { entityType: "AutomationJob", entityId: "job-9", routeTo: "/automation-jobs" }
    };
    renderWithRouter(<ProvenanceLinks {...provenanceFromActivity(item)} />);
    expect(screen.getByRole("link", { name: /AutomationJob #job-9/i })).toHaveAttribute("href", "/automation-jobs");
    expect(screen.getByText("Local Runner")).toBeInTheDocument();
  });
});
