import type { LanguageCode } from "./i18n";

/**
 * Semantic translation keys (M22 — Mission Control i18n Foundation, Phase 1).
 *
 * Unlike the legacy display-text dictionary in `i18n.tsx` (which matches whole
 * English strings at runtime via a DOM observer), these are *semantic keys* a
 * component asks for explicitly via `tk("inbox.title")`. This is the migration
 * target: pages render the same content from keys in any language, so dynamic
 * text, interpolation, and Thai layout fit are all under the component's control.
 *
 * Phase 1 scope: Dashboard (`dashboard.*`) and Inbox (`inbox.*`) static chrome,
 * plus the shared enum/provenance keys those pages render (`risk.*`, `state.*`,
 * `severity.*`, `entity.*`, `provenance.*`). Server-provided prose (a record's
 * title / detail / nextAction) is intentionally NOT keyed — it is data, not
 * chrome. See `docs/MISSION_CONTROL_I18N_KEYS.md` for the per-page inventory and
 * the covered-vs-deferred boundary.
 *
 * Invariant: every `en` value must equal the literal currently rendered, so the
 * existing English snapshot/text assertions keep passing while Thai is added.
 */
export const MESSAGES: Record<LanguageCode, Record<string, string>> = {
  en: {
    // ── Shared: provenance row labels (ProvenanceLinks) ──────────────────────
    "provenance.source": "Source",
    "provenance.generatedBy": "Generated By",
    "provenance.related": "Related",
    "provenance.updated": "Updated",

    // ── Shared: risk labels (raw enum kept in tooltip) ───────────────────────
    "risk.CRITICAL": "Critical",
    "risk.HIGH": "High",
    "risk.MEDIUM": "Medium",
    "risk.LOW": "Low",

    // ── Shared: abstract-state labels (raw enum kept in tooltip) ─────────────
    "state.AWAITING_INPUT": "Awaiting input",
    "state.AWAITING_DECISION": "Awaiting decision",
    "state.AWAITING_ACTION": "Awaiting action",
    "state.BLOCKED": "Blocked",

    // ── Shared: severity labels (raw enum kept in tooltip) ───────────────────
    "severity.CRITICAL": "Critical",
    "severity.WARNING": "Warning",
    "severity.INFO": "Info",

    // ── Shared: entity-type labels (fallback humanizes unknown types) ────────
    "entity.WorkOrder": "Work Order",
    "entity.AutomationJob": "Automation Job",
    "entity.PatchArtifact": "Patch Artifact",
    "entity.AgentRunner": "Agent Runner",
    "entity.HandoffBrief": "Handoff Brief",
    "entity.AgentKnowledgeCandidate": "Agent Knowledge Candidate",
    "entity.CouncilSession": "Council Session",

    // ── Inbox ────────────────────────────────────────────────────────────────
    "inbox.eyebrow": "Kingdom Inbox",
    "inbox.title": "What should the King do next?",
    "inbox.description":
      "Live next actions across work orders, automation jobs, council output, project context, and reports.",
    "inbox.descriptionShort": "Live next actions from the Kingdom's source-of-truth pages.",
    "inbox.refresh": "Refresh",
    "inbox.refreshing": "Refreshing...",
    "inbox.retry": "Retry",
    "inbox.computed": "Computed {date}",
    "inbox.noAutoPolling": "No auto-polling",
    "inbox.unavailableTitle": "Inbox Unavailable",
    "inbox.unavailableMessage": "Unable to load Kingdom Inbox.",
    "inbox.contextNotFresh": "Context is {status} after refresh — check project local docs.",
    "inbox.stat.pending": "Pending",
    "inbox.stat.critical": "Critical",
    "inbox.stat.high": "High",
    "inbox.stat.blocked": "Blocked",
    "inbox.stat.escalated": "Escalated",
    "inbox.topActionTitle": "Top Action",
    "inbox.emptyTitle": "No pending royal actions.",
    "inbox.emptyDescription": "The Kingdom has no pending next actions.",
    "inbox.whyLabel": "Why am I seeing this?",
    "inbox.recommendedAction": "Recommended Action",
    "inbox.sourceOfTruth": "Source of Truth",
    "inbox.openEntity": "Open {entity}",
    "inbox.priorityScore": "Priority Score",
    "inbox.observed": "Observed {age}",
    "inbox.priorityAria": "Priority {priority}",
    "inbox.openSource": "Open source",
    "inbox.priority": "Priority",
    "inbox.filters": "Filters",
    "inbox.filterRisk": "Risk",
    "inbox.allRisks": "All risks",
    "inbox.filterEntity": "Entity Type",
    "inbox.allEntities": "All entities",
    "inbox.escalatedOnly": "Escalated only",
    "inbox.blockedOnly": "Blocked only",
    "inbox.clearFilters": "Clear Filters",
    "inbox.escalated": "Escalated",
    "inbox.blocking": "Blocking",
    "inbox.sourceRefTitle": "Source of Truth References",
    "inbox.actionQueueTitle": "Action Queue ({count})",
    "inbox.totalCount": "{count} total",
    "inbox.noMatchTitle": "No actions match these filters.",
    "inbox.noMatchDescription": "Clear filters to review the full Kingdom Inbox.",
    "inbox.riskGroup.CRITICAL": "Act now",
    "inbox.riskGroup.HIGH": "Review soon",
    "inbox.riskGroup.MEDIUM": "Keep moving",
    "inbox.riskGroup.LOW": "Lower urgency",
    "inbox.age.m": "{n}m ago",
    "inbox.age.h": "{n}h ago",
    "inbox.age.d": "{n}d ago",
    "inbox.source.WorkOrder.label": "Work Orders",
    "inbox.source.WorkOrder.desc": "Implementation queue, handoffs, reports, and review state.",
    "inbox.source.AutomationJob.label": "Automation Jobs",
    "inbox.source.AutomationJob.desc": "Runner jobs, patch validation, approval, and execution state.",
    "inbox.source.CouncilSession.label": "Royal Command",
    "inbox.source.CouncilSession.desc": "Council progress, synthesis, and created work orders.",
    "inbox.source.ProjectContext.label": "Projects",
    "inbox.source.ProjectContext.desc": "Project context, source documents, and local docs bindings.",
    "inbox.source.RoyalBrief.label": "Royal Brief",
    "inbox.source.RoyalBrief.desc": "Generated daily summary and decisions needing review.",
    "inbox.source.Report.label": "Reports",
    "inbox.source.Report.desc": "Generated reports, artifacts, and supporting analysis.",

    // ── Dashboard ──────────────────────────────────────────────────────────
    "dashboard.eyebrow": "Command Center",
    "dashboard.title": "Mission Control",
    "dashboard.description":
      "What the King should do next, why it matters, which source record caused it, and where to inspect or act.",
    "dashboard.issueDecree": "Issue Royal Decree",
    "dashboard.missionControl": "Mission Control",
    "dashboard.actionInbox": "Action Inbox",
    "dashboard.whatNext": "What should the King do next?",
    "dashboard.openAction": "Open action",
    "dashboard.openSource": "Open source",
    "dashboard.sourcePrefix": "Source:",
    "dashboard.contextPrefix": "Context:",
    "dashboard.section.actionQueue": "Action Queue",
    "dashboard.section.activeWork": "Active Work",
    "dashboard.section.needsReview": "Needs Review",
    "dashboard.section.blockedWarnings": "Blocked / Warnings",
    "dashboard.section.recentActivity": "Recent Activity",
    "dashboard.metric.actionQueue": "Action Queue",
    "dashboard.metric.activeWork": "Active Work",
    "dashboard.metric.needsReview": "Needs Review",
    "dashboard.metric.blockedWarnings": "Blocked / Warnings",
    "dashboard.mcUnavailableTitle": "Mission Control unavailable",
    "dashboard.mcUnavailableDesc":
      "Open Work Orders, Automation Jobs, and Providers directly while this control plane loads.",
    "dashboard.noQueuedTitle": "No queued actions",
    "dashboard.noQueuedDesc": "No source records currently need a King decision.",
    "dashboard.noActiveTitle": "No active work",
    "dashboard.noActiveDesc": "Mission Control will show active Work Orders and running Automation Jobs here.",
    "dashboard.noReviewTitle": "No results need review",
    "dashboard.noReviewDesc":
      "Agent review summaries and runner results will appear here when they need a decision.",
    "dashboard.noBlockedTitle": "No blockers or warnings",
    "dashboard.noBlockedDesc":
      "Context, provider, and execution warnings will appear here from their owning source records.",
    "dashboard.noRecentTitle": "No recent activity",
    "dashboard.noRecentDesc": "Recent agent and execution activity will appear here from source records.",
    "dashboard.loading": "Summoning royal briefings...",
    "dashboard.activityStream": "Operations Activity Stream",
    "dashboard.operationsCenter": "Operations Center"
  },
  th: {
    // ── Shared: provenance row labels ────────────────────────────────────────
    "provenance.source": "แหล่งที่มา",
    "provenance.generatedBy": "สร้างโดย",
    "provenance.related": "ที่เกี่ยวข้อง",
    "provenance.updated": "อัปเดตเมื่อ",

    // ── Shared: risk labels ──────────────────────────────────────────────────
    "risk.CRITICAL": "วิกฤต",
    "risk.HIGH": "สูง",
    "risk.MEDIUM": "ปานกลาง",
    "risk.LOW": "ต่ำ",

    // ── Shared: abstract-state labels ────────────────────────────────────────
    "state.AWAITING_INPUT": "รอข้อมูล",
    "state.AWAITING_DECISION": "รอการตัดสินใจ",
    "state.AWAITING_ACTION": "รอดำเนินการ",
    "state.BLOCKED": "ถูกบล็อก",

    // ── Shared: severity labels ──────────────────────────────────────────────
    "severity.CRITICAL": "วิกฤต",
    "severity.WARNING": "คำเตือน",
    "severity.INFO": "ข้อมูล",

    // ── Shared: entity-type labels ───────────────────────────────────────────
    "entity.WorkOrder": "ใบสั่งงาน",
    "entity.AutomationJob": "งานอัตโนมัติ",
    "entity.PatchArtifact": "แพตช์",
    "entity.AgentRunner": "ตัวรันเอเจนต์",
    "entity.HandoffBrief": "เอกสารส่งมอบงาน",
    "entity.AgentKnowledgeCandidate": "ตัวเลือกความรู้เอเจนต์",
    "entity.CouncilSession": "การประชุมสภา",

    // ── Inbox ────────────────────────────────────────────────────────────────
    "inbox.eyebrow": "กล่องงานราชอาณาจักร",
    "inbox.title": "กษัตริย์ควรทำสิ่งใดต่อไป?",
    "inbox.description":
      "งานถัดไปแบบเรียลไทม์จากใบสั่งงาน งานอัตโนมัติ ผลการประชุมสภา บริบทโปรเจกต์ และรายงาน",
    "inbox.descriptionShort": "งานถัดไปแบบเรียลไทม์จากหน้าต้นทางข้อมูลของราชอาณาจักร",
    "inbox.refresh": "รีเฟรช",
    "inbox.refreshing": "กำลังรีเฟรช...",
    "inbox.retry": "ลองใหม่",
    "inbox.computed": "คำนวณเมื่อ {date}",
    "inbox.noAutoPolling": "ไม่มีการดึงข้อมูลอัตโนมัติ",
    "inbox.unavailableTitle": "กล่องงานใช้งานไม่ได้",
    "inbox.unavailableMessage": "ไม่สามารถโหลดกล่องงานราชอาณาจักรได้",
    "inbox.contextNotFresh": "บริบทเป็น {status} หลังรีเฟรช — ตรวจสอบเอกสารโลคัลของโปรเจกต์",
    "inbox.stat.pending": "รอดำเนินการ",
    "inbox.stat.critical": "วิกฤต",
    "inbox.stat.high": "สูง",
    "inbox.stat.blocked": "ถูกบล็อก",
    "inbox.stat.escalated": "ยกระดับ",
    "inbox.topActionTitle": "งานสำคัญสูงสุด",
    "inbox.emptyTitle": "ไม่มีงานหลวงที่รอดำเนินการ",
    "inbox.emptyDescription": "ราชอาณาจักรไม่มีงานถัดไปที่รอดำเนินการ",
    "inbox.whyLabel": "ทำไมจึงเห็นรายการนี้?",
    "inbox.recommendedAction": "การดำเนินการที่แนะนำ",
    "inbox.sourceOfTruth": "แหล่งข้อมูลต้นทาง",
    "inbox.openEntity": "เปิด {entity}",
    "inbox.priorityScore": "คะแนนความสำคัญ",
    "inbox.observed": "พบเมื่อ {age}",
    "inbox.priorityAria": "ความสำคัญ {priority}",
    "inbox.openSource": "เปิดแหล่งที่มา",
    "inbox.priority": "ความสำคัญ",
    "inbox.filters": "ตัวกรอง",
    "inbox.filterRisk": "ความเสี่ยง",
    "inbox.allRisks": "ทุกความเสี่ยง",
    "inbox.filterEntity": "ประเภทเอนทิตี",
    "inbox.allEntities": "ทุกเอนทิตี",
    "inbox.escalatedOnly": "เฉพาะที่ยกระดับ",
    "inbox.blockedOnly": "เฉพาะที่ถูกบล็อก",
    "inbox.clearFilters": "ล้างตัวกรอง",
    "inbox.escalated": "ยกระดับ",
    "inbox.blocking": "กำลังบล็อก",
    "inbox.sourceRefTitle": "แหล่งข้อมูลต้นทางอ้างอิง",
    "inbox.actionQueueTitle": "คิวงาน ({count})",
    "inbox.totalCount": "ทั้งหมด {count}",
    "inbox.noMatchTitle": "ไม่มีงานตรงกับตัวกรองนี้",
    "inbox.noMatchDescription": "ล้างตัวกรองเพื่อดูกล่องงานทั้งหมด",
    "inbox.riskGroup.CRITICAL": "ดำเนินการทันที",
    "inbox.riskGroup.HIGH": "ตรวจสอบเร็ว ๆ นี้",
    "inbox.riskGroup.MEDIUM": "เดินหน้าต่อ",
    "inbox.riskGroup.LOW": "ความเร่งด่วนต่ำ",
    "inbox.age.m": "{n} นาทีที่แล้ว",
    "inbox.age.h": "{n} ชม.ที่แล้ว",
    "inbox.age.d": "{n} วันที่แล้ว",
    "inbox.source.WorkOrder.label": "ใบสั่งงาน",
    "inbox.source.WorkOrder.desc": "คิวการพัฒนา การส่งมอบ รายงาน และสถานะการตรวจ",
    "inbox.source.AutomationJob.label": "งานอัตโนมัติ",
    "inbox.source.AutomationJob.desc": "งาน runner การตรวจแพตช์ การอนุมัติ และสถานะการรัน",
    "inbox.source.CouncilSession.label": "ศูนย์บัญชาการหลวง",
    "inbox.source.CouncilSession.desc": "ความคืบหน้าสภา บทสรุป และใบสั่งงานที่สร้าง",
    "inbox.source.ProjectContext.label": "โปรเจกต์",
    "inbox.source.ProjectContext.desc": "บริบทโปรเจกต์ เอกสารต้นทาง และการผูกเอกสารโลคัล",
    "inbox.source.RoyalBrief.label": "สรุปประจำวันหลวง",
    "inbox.source.RoyalBrief.desc": "สรุปประจำวันที่สร้างและการตัดสินใจที่ต้องตรวจ",
    "inbox.source.Report.label": "รายงาน",
    "inbox.source.Report.desc": "รายงานที่สร้าง อาร์ติแฟกต์ และการวิเคราะห์สนับสนุน",

    // ── Dashboard ──────────────────────────────────────────────────────────
    "dashboard.eyebrow": "ศูนย์บัญชาการ",
    "dashboard.title": "ศูนย์บัญชาการภารกิจ",
    "dashboard.description":
      "สิ่งที่กษัตริย์ควรทำต่อไป เหตุผลที่สำคัญ บันทึกต้นทางที่ทำให้เกิด และที่ที่จะตรวจสอบหรือดำเนินการ",
    "dashboard.issueDecree": "ออกพระราชโองการ",
    "dashboard.missionControl": "ศูนย์บัญชาการภารกิจ",
    "dashboard.actionInbox": "กล่องงาน",
    "dashboard.whatNext": "กษัตริย์ควรทำสิ่งใดต่อไป?",
    "dashboard.openAction": "เปิดงาน",
    "dashboard.openSource": "เปิดแหล่งที่มา",
    "dashboard.sourcePrefix": "แหล่งที่มา:",
    "dashboard.contextPrefix": "บริบท:",
    "dashboard.section.actionQueue": "คิวงาน",
    "dashboard.section.activeWork": "งานที่กำลังทำ",
    "dashboard.section.needsReview": "ต้องตรวจสอบ",
    "dashboard.section.blockedWarnings": "ถูกบล็อก / คำเตือน",
    "dashboard.section.recentActivity": "กิจกรรมล่าสุด",
    "dashboard.metric.actionQueue": "คิวงาน",
    "dashboard.metric.activeWork": "งานที่กำลังทำ",
    "dashboard.metric.needsReview": "ต้องตรวจสอบ",
    "dashboard.metric.blockedWarnings": "ถูกบล็อก / คำเตือน",
    "dashboard.mcUnavailableTitle": "ศูนย์บัญชาการภารกิจไม่พร้อมใช้งาน",
    "dashboard.mcUnavailableDesc":
      "เปิดใบสั่งงาน งานอัตโนมัติ และผู้ให้บริการโดยตรงระหว่างที่ระบบกำลังโหลด",
    "dashboard.noQueuedTitle": "ไม่มีงานในคิว",
    "dashboard.noQueuedDesc": "ขณะนี้ไม่มีบันทึกต้นทางที่ต้องการการตัดสินใจจากกษัตริย์",
    "dashboard.noActiveTitle": "ไม่มีงานที่กำลังทำ",
    "dashboard.noActiveDesc": "ศูนย์บัญชาการภารกิจจะแสดงใบสั่งงานที่กำลังทำและงานอัตโนมัติที่กำลังรันที่นี่",
    "dashboard.noReviewTitle": "ไม่มีผลลัพธ์ที่ต้องตรวจสอบ",
    "dashboard.noReviewDesc": "สรุปการตรวจของเอเจนต์และผลลัพธ์ของ runner จะปรากฏที่นี่เมื่อต้องการการตัดสินใจ",
    "dashboard.noBlockedTitle": "ไม่มีตัวบล็อกหรือคำเตือน",
    "dashboard.noBlockedDesc": "คำเตือนด้านบริบท ผู้ให้บริการ และการรันจะปรากฏที่นี่จากบันทึกต้นทางที่เกี่ยวข้อง",
    "dashboard.noRecentTitle": "ไม่มีกิจกรรมล่าสุด",
    "dashboard.noRecentDesc": "กิจกรรมล่าสุดของเอเจนต์และการรันจะปรากฏที่นี่จากบันทึกต้นทาง",
    "dashboard.loading": "กำลังเรียกสรุปข้อมูลหลวง...",
    "dashboard.activityStream": "สตรีมกิจกรรมปฏิบัติการ",
    "dashboard.operationsCenter": "ศูนย์ปฏิบัติการ"
  }
};

/**
 * Resolve a semantic key for a language with `{var}` interpolation.
 * Falls back to the English value, then to the key itself (so a missing key is
 * visible in dev rather than rendering blank).
 */
export function resolveMessage(
  key: string,
  language: LanguageCode,
  vars?: Record<string, string | number>
): string {
  const template = MESSAGES[language]?.[key] ?? MESSAGES.en[key] ?? key;
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match
  );
}
